### ISSUE TITLE
List all needed environment variables

### ISSUE THREAD

**Issue by NNTin** [JossMoff/RedditMusicBot#1]
I found 3 additional environment variables which were not listed in the README.md:

`SUBREDDIT`, `MONTH_UPVOTE_THRESHOLD` and `ALL_UPVOTE_THRESHOLD`. I'm unsure if there are more.

Please also list them in the README.md so self hosters can find the necessary resources more easily.

**Comment by jossmoff** [comment]
Fixed issue in README and clarified the 2 more obscure config variables:
- ALL_UPVOTE_THRESHOLD
- MONTH_UPVOTE_THRESHOLD

By changing README.md using @NNTin's image in #2 .

Joss
